### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by trajano** [rjo1970/dumbster#10]
Can you release this to Maven Central?

**Comment by rjo1970** [comment]
I had been avoiding that since there is already a dumbster artifact in Maven Central.  Since I am not a Maven user in general, it wasn't a problem.  I presume I would need to re-name my project.

**Comment by trajano** [comment]
NP, I found another alternative that is compatible with Maven.

```
<dependency>
        <groupId>com.icegreen</groupId>
        <artifactId>greenmail</artifactId>
        <version>1.3.1b</version>
        <scope>test</scope>
    </dependency>
```

**Comment by yegor256** [comment]
+1 would be great to see **this** version of dumbster in Maven. At the moment, the latest we have there is 1.6:

``` xml
        <dependency>
            <groupId>dumbster</groupId>
            <artifactId>dumbster</artifactId>
            <version>1.6</version>
            <scope>test</scope>
        </dependency>
```

**Comment by malkusch** [comment]
+1
When it comes to test mail transport, dumbster is still a famous name. It was also my choice for testing and I ended up wasting one day with the [broken](http://sourceforge.net/p/dumbster/bugs/15/) dumbster-1.6 from maven central. Please add your dumbster into maven central.

**Comment by olivierlemasle** [comment]
+1
There is no need to rename your project, since you don't use the same Maven coordinates (original groupId is `dumbster`, your fork's groupId is `org.github.rjo1970`.)

Would you like some help to release it to Maven Central? I can help if you want...

**Comment by yegor256** [comment]
maybe this article will help you http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

**Comment by rjo1970** [comment]
I am not in a position to maintain this project right now.  I would recommend someone fork it and take care of the Maven Central offering.

**Comment by coopernurse** [comment]
Done and done.  Just forked and published it.  I tweaked some javadoc in the source files to appease some of the CLI release tools, but other than that, no changes from the master repo here.

``` xml
<dependency>
    <groupId>com.bitmechanic</groupId>
    <artifactId>dumbster</artifactId>
    <version>1.9.0.2</version>
</dependency>
```

**Comment by rjo1970** [comment]
Glad to hear it.  Thank you!
