### ISSUE TITLE
Truncated Subject line

### ISSUE THREAD

**Issue by rjo1970** [rjo1970/dumbster#2]
Got a report that Subject lines over length 62 are truncated.

**Comment by rjo1970** [comment]
I added tests both to MailMessageTest and SimpleSmtpServerTest.  Both accept and return 500-character Subject lines.

**Comment by nguillaumin** [comment]
Hi,

I just came across this issue, except that my subject lines are truncated to 64 characters instead of 64.

Strangely Dumbster's unit tests pass successfully on my setup so it must come from the way the mail is sent. I'll investigate.

Nico
