### ISSUE TITLE
Dumbster doesn't comply to the 78 characters per line limit

### ISSUE THREAD

**Issue by nguillaumin** [rjo1970/dumbster#4]
(This is a continuation of issue #2 that I cannot re-open.)

I finally found from where these Subject line truncation happened. According to the [RFC 2822](http://www.ietf.org/rfc/rfc2822.txt) section 2.2.3 the lines of a message shouldn't be longer than 78 characters. For that reason it's possible to put a CRLF in any header line that is longer than 78, as I observed when looking at the offending email source in Thunderbird:

```
...
Message-ID: <9637901.1.1314596564608.JavaMail.Administrator@auto-win2003>
Subject: Funnelback Reports for: Se2-ReportingEmail (_default) [29 August
 2011]
MIME-Version: 1.0
...
```

It turns out that the `mail.jar` that comes with Dumbster (and used for the unit tests) seems to be v1.3.0, whereas my app is using v1.4.2. When I upgrade `mail.jar` to 1.4.2 on Dumbster I can reproduce the problem. I've created a branch showing it here: https://github.com/nguillaumin/dumbster/tree/headers-linebreak

So I guess the header / data parsing code will need to be updated to account for that 78 characters limit...

Cheers,

Nico

**Comment by rjo1970** [comment]
Thanks for the great feedback!  I'll try to take a look at the problem this week.

**Comment by rjo1970** [comment]
I've got a candidate solution pushed out there.  I seem to be having a problem with ending /r/n sequences going away- likely due to my state machine goofing up.  I'd really appreciate any feedback on how it is working and how I might have broken it for others.  Thanks!

**Comment by nguillaumin** [comment]
Thanks, I just tried it and it seems to work perfectly for me !
