### ISSUE TITLE
Problem with multi-line body

### ISSUE THREAD

**Issue by jbellassai** [rjo1970/dumbster#9]
The appendBody method in MailMessageImpl is not honoring newlines in multi-lined messages.  The origin of the problem is that the readLine() method in BufferedReader strips the newline so it is not being added to the StringBuffer.  After playing around with it, the following seems to work (at least for my use case):

```
public void appendBody(String line) {
    if(body.length() > 0 && line.length() > 0 && !"\n".equals(line)) {
        body.append('\n');
    }
    body.append(line);
}
```

**Comment by rjo1970** [comment]
Thanks for the fix!  I've added it and a test.
